shared_snowflake_profile:
  outputs:
    dev:
      type: snowflake
      # These are placeholders - Snowflake native execution doesn't use them
      account: dummy
      user: dummy 
      password: dummy
      # These inherit from Snowflake session context
      warehouse: HHS_FIVETRAN_WAREHOUSE
      database: HHS_FIVETRAN_INT_DB
      schema: FIVETRAN_RAW
      role: __HHS_FIVETRAN_INT_OWN
      threads: 2
  target: dev
