shared_snowflake_profile:
  outputs:
    dev:
      type: snowflake
      # These are placeholders - Snowflake native execution doesn't use them
      account: dummy
      user: dummy 
      password: dummy
      # These inherit from Snowflake session context
      warehouse: HHS_PHSD_MIDIS_DEV_ELT_WH
      database: HHS_WRKSPC_DB
      schema: CSW191
      role: HHS_SFLK_PHSD_MIDIS_ANALYST_DEV
      threads: 2
  target: dev
