shared_snowflake_profile:
  outputs:
    dev:
      type: snowflake
      # These are placeholders - Snowflake native execution doesn't use them
      account: MONTANA-HHS
      user: "CSW191@MT.GOV"
      SNOWFLAKE_PRIVATE_KEY_PATH:"-----BEGIN PRIVATE KEY-----
MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDQWLez1/kuhYZX
/UUmQHV6LA/FxWpWtD9nvbdEnrLIfPEQ10qHY8JThFCeoVUhUVWylvdOHjm9UWVi
EOux37B2iLK6TdOZFWrifRLh56eCY2HKHWgXkAP1DxSTZMRK5ZpLu/bVMZaoO8DX
KAkrB0mTZ/1tL7c4y6liDP7ccEZ5XwlzGO81MrK1S9R/ipuVhj6g6/VHVgz/Tpeh
BTHFmk4803Wmu4V56uREPdkyCHlbgIfFwLb1j+Mc4NdgDtqS9LcYLzI1MJba6BVa
m/YvhDBsnMWzy0ailk4/rcdei1AlIc/iUjc3NbCZIt95BHDhkLml3cKXI9uBOMAT
t3dDqTiCLYdHUovT908SDSr6iBDtHBk+vzfBUg+Ox+tb0yygIOca7tQDIRDZXU/M
zAP8Qr9jqnD8kZhpfcVZhn8uqqj1L65RTsMR2klGcn0moijLhvggNw2bH0uADWUa
VaLJs1I03wEPgfqO2xX3wJ/Caixuyfd5M9knGmyiu5YJyVViehQXimfb64IMwu9x
Cyy5/mPReKl+0NRXmf+ZhLSJr7pi2Lf7/1oyJnDaSBEtDHaupUUJmxAhiz/jg5tY
nuGZiHHBXMrLcKjFhY/flhM9xQzSbMglkpG7MYXANWOFjdXuDQ4gx8Nc38IQ1xTk
Tez+x0M/TewJTFaiIuQ0Sltr86k3dQIDAQABAoICAAQsKq2q3x4r5WdgtqBP/SpP
tJco33rSDE0HEyMILJtwSSGltiPk/xDOHxE2OO68YsN7W4OQfmaIuUeQADBlQvL0
xOOPSHQR5jyX9adZjNTDKcOy+BE0vKeNQEO9amL3mzH2Fzjoz9QZskB82EYo1LPj
isNDh99W0NMaYIZIp1ip6xYHg07k74hK9vwA6iHB+QIfB6AAnK0GRWofoQIMl5GH
SJ1otwEcj6rANFfYrJmFBvMSa3eahJlg9V9CnOUBiqMs2swO546FxFu2sOT9uDyM
nTb/FLCP4wxKbio6DwZXWYL2U43DAQDoHmKdkKcrz1P/j3SYbr51RP+AFp7fxjZn
7qstokAiCQAwODyd7rQcuY1i7IX6eh7dOapqQOpZzVzc+BdGRP0MnZKNu8mqBKBH
cRtPV/i/+/hj+JexUdVxuMc8a01U11cymAKXTFk0U9ukwA8CH5DneyM1fKdQAKjQ
6lJ2JGutJpvDXbEALnWsf93Tvl9qoC19SjpmH5zrW7hRh5jDs2a5Ep4iV2iop9sA
ryx2zvvq3f66FG+e7MGtxmY30IzIMz6RVyjIsTZstTZT+JZ0W14WRGaxeXQ8DyxI
40KlSNLkklRCJqI11FrOELAG98OkNvY0gweNHxCRKAwDNiYh+ziy+CnvKuaEv6lZ
Zsi/bnIgEP2+Yqs5jxgxAoIBAQD20kT5EM1Y2V/a9OuefXVr3qeJtthHWJTi3aZL
+3SDhyfG5WFpZYEsbsWeMgd1NPY9L5/zFaMYnuxFRYOb0PPD07mQKB2v90pnKlat
MBNz4HxLarS486Ye+9Bv/iz4+u53eNutDoVZaCQklhiPZoa7VAA4o88LV7G0RdfR
c+tsYyE1dECkkuLInIfUB1sycLn2LOCX/mFrMLu4BwxuBwOlYTN4ZD6azbte+Pka
/Ckouwa5nAsR5C7Dm52Gne/Imd8oz9zii19OmfRFiTPHYBZljPLezthgGYVW7JHN
/qNq+Ng5eQFoVeRHJj28e8GDrCy+ES9s8/kQOvrY1gY4NQcNAoIBAQDYGCtZGrfD
lxpn9h1QG8wPekCD1TCfzzFqddZP1OR6OX5B+t9IPu7xRQ3yKqAXsyJq7+Fb2N7I
378WtUvkUXf/2gQOFGtos7IiTG/u79gHLqlcVZxX/h+/yWj7nNl0a/xFkRnluBei
Mkfc5mLI1h+nWl0RZ6KRQfmd8fNKF0oyuR6octFYQtqyL/UGFUdg3ZsPw68Y26vm
EoeS6W1jLN3HwUfZ/69T2TG3UChE9avUL7J8PX0tbADjyuFyJww+71HbIJHNHwXI
tyWjQq29lsPxfCGB96AEsz4woae/uIjoYCYUWqyUtUgfznyReX4WmLYY2Y3cCCW0
uQ9vS4tU/dgJAoIBAQDlIMfkyyNGEu14TxuYUvE5hUXUg0f9247DmG3zZWiBXWug
qXonpJIo1GBh/iGMPfFFVbvPpst0ZLwDhoepk21n4loGKCd/HjsU0GoMdm/oh4H7
ZQCGHbGeW7fg732CWTgc8rZDzhIesJ201R3RqaTzrARUkET5S5xtNNUn3Mu1H8VJ
YTVNUgpzn1Q8keOoTJtlm72XfA+luWTabrisP5iz4ysr3St8+/WwMcLWuTXgWNbi
YaipIEIFVqYCvQVHHQjcUzLDoAyG5EaucrL9qAbCmPkxu6WEeMyeqBimuXetK3tW
xy12VR4Iqshu/BfmC2SxwTRcmZQh7A7IUs8NSLTVAoIBAAl0DTlprM5WpuYTYzbk
8Glg7L+XrPfgxYWlwAlgA9rA9yAFzIzJjARsA+8rJDPFN2U8NzygYSaieyaQKdDE
K566t+Cxzf0Xl1xewarPPUEbLneGmz9SM6tdMUWImA66xp94eIyPICGNV413Wqz0
iQ/2KQog4YC/RR8+vWjpWeqcJJYz56qXyh9vb6WjeqrnJuhqpBdPTNbUyq+HnKxx
AwbBEtabk9z0LHObgxd5M9oleAZtXjOFfQh6EKDAyo1aRNd0Nkyl5cfhEzlwKk+X
79x5lLGt1oc+HCNefwspFHwt8JyFVvVudMhHbTWj/fsZFSZDJiyRAq1ER0OUJ3VB
YZkCggEAAwmJHr5QE5vHdiOChBw1zsrECMUAjAw5Bw8HohACXgBcO5nHPtVMke3T
85SLL/48kErJJOPtRFzLvJYCzKBaQYXScsysjL3lmeGgDNpblhozeCFTNEbW7M8H
g8dZc4kVQLJnJuX3jVa2FsHCTsnq+nuLBjTBJBrSHldQjUedJXqyy1mKAnS9PAWo
44qR2hBM241MFpS4dLEtoW+fWHIrTIMix8RTUCyFoi/fwgBrjgbNA0ESGoJxo07A
AGpQJu7zr5EtRCt5tNMPp8piWHyI00LW4lNO2DmYMbXoWKy/ytrY3BtBlKRd8kY4
tmyb4EqzwX+dkJL2rRKDMhh+EFP8Xg==
-----END PRIVATE KEY-----
"
      warehouse: HHS_PHSD_MIDIS_DEV_ELT_WH
      database: HHS_WRKSPC_DB
      schema: FIVETRAN_RAW
      role: HHS_SFLK_PHSD_MIDIS_ANALYST_DEV
      threads: 2
  target: dev
